version: "3.8"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 50m

services:
  xukabot:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: docker/images/app/Dockerfile
    container_name: xukabot
    command: sh /xukabot/docker/bin/wait-for-it.sh sh /xukabot/docker/bin/start_rails.sh development
    ports:
      - 3000:3000
    volumes:
      - .:/xukabot:cached
      - bundle:/usr/local/bundle
    environment:
      - XUKA_DATABASE_HOST=mysql
      - XUKA_DATABASE_USERNAME=root
      - XUKA_API_DATABASE_PASSWORD=root
    depends_on:
      - mysql
      - redis
    <<: *default-logging

  sidekiq:
    build:
      context: .
      dockerfile: docker/images/app/Dockerfile
    volumes:
      - .:/xukabot
      - bundle-sidekiq:/usr/local/bundle
    command: sh /xukabot/docker/bin/start_sidekiq.sh development
    depends_on:
      - xukabot
    <<: *default-logging

  mysql:
    image: mysql:5.7
    ports:
      - 53306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    <<: *default-logging

  redis:
    image: redis:4.0
    ports:
      - 56379:6379
    volumes:
      - redis_data:/data
    <<: *default-logging

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 59200:9200
    <<: *default-logging

volumes:
  bundle:
  temp:
  mysql-data:
  redis_data:
  bundle-sidekiq:
  esdata:
