version: "3.8"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 50m

services:
  xukabot:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xukabot
    command: sh /xukabot/docker/bin/wait-for-it.sh sh /xukabot/docker/bin/start_rails.sh development
    ports:
      - 3000:3000
    volumes:
      - .:/xukabot:cached
      - bundle:/usr/local/bundle
    environment:
      - XUKA_DATABASE_HOST=mysql
      - XUKA_DATABASE_USERNAME=root
      - XUKA_API_DATABASE_PASSWORD=root
    depends_on:
      - mysql
      - redis
    <<: *default-logging

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/xukabot
      - bundle-sidekiq:/usr/local/bundle
    command: sh /xukabot/docker/bin/start_sidekiq.sh
    depends_on:
      - xukabot
    <<: *default-logging

  mysql:
    image: mysql:5.7
    ports:
      - 53306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    <<: *default-logging

  redis:
    image: redis:4.0
    ports:
      - 56379:6379
    volumes:
      - redis_data:/data
    <<: *default-logging

volumes:
  bundle:
  temp:
  mysql-data:
  redis_data:
  bundle-sidekiq:
