hook:
  messages:
    default: "¯\\_(ツ)_/¯"
  regex:
    raw_message: !ruby/regexp /\n(?<message>(.|\n)*)/
    create_question: !ruby/regexp /QUESTION:(?<question>(.|\n)*)\nANSWER:(?<answer>(.|\n)*)/
